services:
  frontends:
  - name: Frontend0
    port_in: 49283
    port_out: 51979
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 49283 --port_out 51979 --port_ctrl 63936 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 51979
    port_out: 59806
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 51979 --port_out 59806 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 64635 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 59806
    port_out: 61741
    ctrl_port:
    grpc_port:
    command: encode --port_in 59806 --port_out 61741 --socket_in SUB_CONNECT --port_ctrl
      62478 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 61741
    port_out: 57819
    ctrl_port:
    grpc_port:
    command: index --port_in 61741 --port_out 57819 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 51438 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 59806
    port_out: 57819
    ctrl_port:
    grpc_port:
    command: index --port_in 59806 --port_out 57819 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 53900 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: Reduce
    port_in: 57819
    port_out: 49283
    ctrl_port:
    grpc_port:
    command: route --port_in 57819 --port_out 49283 --socket_out PUSH_CONNECT --port_ctrl
      58884 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:Reduce