services:
  frontends:
  - name: Frontend0
    port_in: 51953
    port_out: 59915
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 51953 --port_out 59915 --port_ctrl 51254 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 59915
    port_out: 58229
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 59915 --port_out 58229 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 59552 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 58229
    port_out: 57116
    ctrl_port:
    grpc_port:
    command: encode --port_in 58229 --port_out 57116 --socket_in SUB_CONNECT --port_ctrl
      49455 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 57116
    port_out: 60851
    ctrl_port:
    grpc_port:
    command: index --port_in 57116 --port_out 60851 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 64456 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 58229
    port_out: 60851
    ctrl_port:
    grpc_port:
    command: index --port_in 58229 --port_out 60851 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 61875 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: Reduce
    port_in: 60851
    port_out: 51953
    ctrl_port:
    grpc_port:
    command: route --port_in 60851 --port_out 51953 --socket_out PUSH_CONNECT --port_ctrl
      64465 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:Reduce