services:
  frontends:
  - name: Frontend0
    port_in: 63014
    port_out: 53011
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 63014 --port_out 53011 --port_ctrl 64822 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 53011
    port_out: 64830
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 53011 --port_out 64830 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 59045 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 64830
    port_out: 53292
    ctrl_port:
    grpc_port:
    command: encode --port_in 64830 --port_out 53292 --socket_in SUB_CONNECT --port_ctrl
      52362 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 53292
    port_out: 52357
    ctrl_port:
    grpc_port:
    command: index --port_in 53292 --port_out 52357 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 52029 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 64830
    port_out: 52357
    ctrl_port:
    grpc_port:
    command: index --port_in 64830 --port_out 52357 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 55020 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: Reduce
    port_in: 52357
    port_out: 63014
    ctrl_port:
    grpc_port:
    command: route --port_in 52357 --port_out 63014 --socket_out PUSH_CONNECT --port_ctrl
      63307 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:Reduce