services:
  frontends:
  - name: Frontend0
    port_in: 51918
    port_out: 57625
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 51918 --port_out 57625 --port_ctrl 64941 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 57625
    port_out: 61487
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 57625 --port_out 61487 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 59715 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 61487
    port_out: 60247
    ctrl_port:
    grpc_port:
    command: encode --port_in 61487 --port_out 60247 --socket_in SUB_CONNECT --port_ctrl
      62369 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 60247
    port_out: 58631
    ctrl_port:
    grpc_port:
    command: index --port_in 60247 --port_out 58631 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 55364 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 61487
    port_out: 58631
    ctrl_port:
    grpc_port:
    command: index --port_in 61487 --port_out 58631 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 55895 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: Reduce
    port_in: 58631
    port_out: 51918
    ctrl_port:
    grpc_port:
    command: route --port_in 58631 --port_out 51918 --socket_out PUSH_CONNECT --port_ctrl
      60182 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:Reduce