services:
  frontends:
  - name: Frontend0
    port_in: 60442
    port_out: 63742
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 60442 --port_out 63742 --port_ctrl 62853 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 63742
    port_out: 61899
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 63742 --port_out 61899 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 51805 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 61899
    port_out: 62648
    ctrl_port:
    grpc_port:
    command: encode --port_in 61899 --port_out 62648 --socket_in SUB_CONNECT --port_ctrl
      60517 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 62648
    port_out: 54305
    ctrl_port:
    grpc_port:
    command: index --port_in 62648 --port_out 54305 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 50136 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 61899
    port_out: 54305
    ctrl_port:
    grpc_port:
    command: index --port_in 61899 --port_out 54305 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 55399 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: Reduce
    port_in: 54305
    port_out: 60442
    ctrl_port:
    grpc_port:
    command: route --port_in 54305 --port_out 60442 --socket_out PUSH_CONNECT --port_ctrl
      53919 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:Reduce