services:
  frontends:
  - name: Frontend0
    port_in: 54283
    port_out: 52854
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 54283 --port_out 52854 --port_ctrl 62861 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 52854
    port_out: 51170
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 52854 --port_out 51170 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 55975 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 51170
    port_out: 49800
    ctrl_port:
    grpc_port:
    command: encode --port_in 51170 --port_out 49800 --socket_in SUB_CONNECT --port_ctrl
      62296 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 49800
    port_out: 52000
    ctrl_port:
    grpc_port:
    command: index --port_in 49800 --port_out 52000 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 50743 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 51170
    port_out: 52000
    ctrl_port:
    grpc_port:
    command: index --port_in 51170 --port_out 52000 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 59199 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 52000
    port_out: 54283
    ctrl_port:
    grpc_port:
    command: route --port_in 52000 --port_out 54283 --socket_out PUSH_CONNECT --port_ctrl
      62057 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce