name: Reduce
port_in: 53498
port_out: 52739
ctrl_port:
grpc_port:
command: route --port_in 53498 --port_out 52739 --socket_out PUSH_CONNECT --port_ctrl
  61602 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
replicas: 1
storage:
memory:
cpu:
image: gnes-router:Reduce