services:
  frontends:
  - name: Frontend0
    port_in: 58620
    port_out: 65351
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 58620 --port_out 65351 --port_ctrl 54380 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 65351
    port_out: 57072
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 65351 --port_out 57072 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 53518 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 57072
    port_out: 61543
    ctrl_port:
    grpc_port:
    command: encode --port_in 57072 --port_out 61543 --socket_in SUB_CONNECT --port_ctrl
      55477 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 61543
    port_out: 61586
    ctrl_port:
    grpc_port:
    command: index --port_in 61543 --port_out 61586 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 56793 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 57072
    port_out: 61586
    ctrl_port:
    grpc_port:
    command: index --port_in 57072 --port_out 61586 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 62869 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 61586
    port_out: 58620
    ctrl_port:
    grpc_port:
    command: route --port_in 61586 --port_out 58620 --socket_out PUSH_CONNECT --port_ctrl
      58308 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce