frontends:
- name: Frontend0
  port_in: 60580
  port_out: 56716
  ctrl_port:
  grpc_port: 8800
  command: frontend --port_in 60580 --port_out 56716 --port_ctrl 52432 --parallel_backend
    process
  replicas: 1
  storage:
  memory:
  cpu:
  image: gnes-frontend:Frontend0
preprocessors:
- name: sent_split
  port_in: 56716
  port_out: 50007
  ctrl_port:
  grpc_port:
  command: preprocess --port_in 56716 --port_out 50007 --socket_in PULL_CONNECT --socket_out
    PUB_BIND --port_ctrl 50026 --parallel_backend process --yaml_path ../../../services/preprocessors/sent_split/json_mode.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-preprocessor:sent_split
encoders:
- name: siamese_bert
  port_in: 50007
  port_out: 58311
  ctrl_port:
  grpc_port:
  command: encode --port_in 50007 --port_out 58311 --socket_in SUB_CONNECT --port_ctrl
    63026 --parallel_backend process --yaml_path ../../../services/encoders/siamese_bert/dim_64.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-encoder:siamese_bert
- name: text_byte
  port_in: 50007
  port_out: 59267
  ctrl_port:
  grpc_port:
  command: encode --port_in 50007 --port_out 59267 --socket_in SUB_CONNECT --port_ctrl
    61076 --parallel_backend process --yaml_path ../../../services/encoders/text_byte/max_256.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-encoder:text_byte
indexers:
- name: faiss_cpu
  port_in: 58311
  port_out: 51290
  ctrl_port:
  grpc_port:
  command: index --port_in 58311 --port_out 51290 --socket_in PULL_CONNECT --socket_out
    PUSH_CONNECT --port_ctrl 52549 --parallel_backend process --yaml_path ../../../services/indexers/faiss_cpu/base.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-indexer:faiss_cpu
- name: keyword
  port_in: 59267
  port_out: 51290
  ctrl_port:
  grpc_port:
  command: index --port_in 59267 --port_out 51290 --socket_in PULL_CONNECT --socket_out
    PUSH_CONNECT --port_ctrl 50681 --parallel_backend process --yaml_path ../../../services/indexers/keyword/base.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-indexer:keyword
- name: lvdb
  port_in: 50007
  port_out: 51290
  ctrl_port:
  grpc_port:
  command: index --port_in 50007 --port_out 51290 --socket_in SUB_CONNECT --socket_out
    PUSH_CONNECT --port_ctrl 51624 --parallel_backend process --yaml_path ../../../services/indexers/lvdb/base.yml
  replicas: 2
  storage:
  memory:
  cpu:
  image: gnes-indexer:lvdb
routers:
- name: Reduce
  port_in: 51290
  port_out: 60580
  ctrl_port:
  grpc_port:
  command: route --port_in 51290 --port_out 60580 --socket_out PUSH_CONNECT --port_ctrl
    57977 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
  replicas: 1
  storage:
  memory:
  cpu:
  image: gnes-router:Reduce