
{{- define "service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}-{{ .model }}
spec:
  selector:
    app: {{ .app }}-{{ .model }}
  clusterIP: None
  ports:
    {{- if .port_in }}
    - name: in
      port: {{ .port_in }}
      protocol: TCP
    {{- end }}
    {{- if .port_out }}
    - name: out
      port: {{ .port_out }}
      protocol: TCP
    {{- end -}}
    {{- if .grpc_port }}
    - name: grpc
      port: {{ .grpc_port }}
      protocol: TCP
    {{- end -}}
    {{- if .grpc_port }}
    - name: ctrl
      port: {{ .port_ctrl }}
      protocol: TCP
    {{- end -}}
  {{ if .load_balancer }}
  type: LoadBalancer
  {{ end }}
{{- end -}}