services:
  httpclient:
  - name: http
    app: httpclient
    model: http
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-http
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 55132
    port_out: 54753
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '55132'
    - --port_out
    - '54753'
    - --port_ctrl
    - '55821'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: Router0
    app: router
    model: base
    port_in: 54753
    port_out: 62859
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '54753'
    - --port_out
    - '62859'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '54268'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: Router1
    app: router
    model: base
    port_in: 62859
    port_out: 50960
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '62859'
    - --port_out
    - '50960'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '58464'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 50960
    port_out: 55132
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '50960'
    - --port_out
    - '55132'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '50002'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  preprocessor:
  - name: unary
    app: preprocessor
    model: unary
    port_in: 62859
    port_out: 53105
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62859'
    - --port_out
    - '53105'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '52107'
    - --parallel_backend
    - process
    - --yaml_path
    - text.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-preprocessor:latest-unary
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 53105
    port_out: 54480
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '53105'
    - --port_out
    - '54480'
    - --socket_in
    - PULL_CONNECT
    - --port_ctrl
    - '65125'
    - --parallel_backend
    - process
    - --yaml_path
    - max256.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 54480
    port_out: 50960
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '54480'
    - --port_out
    - '50960'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '64221'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword