services:
  httpclient:
  - name: http
    app: httpclient
    model: http
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-http
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 58386
    port_out: 64199
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '58386'
    - --port_out
    - '64199'
    - --port_ctrl
    - '65253'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: Router0
    app: router
    model: base
    port_in: 64199
    port_out: 56678
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '64199'
    - --port_out
    - '56678'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '59513'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: Router1
    app: router
    model: base
    port_in: 56678
    port_out: 62214
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '56678'
    - --port_out
    - '62214'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '63892'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 62214
    port_out: 58386
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62214'
    - --port_out
    - '58386'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '51630'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 56678
    port_out: 55027
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '56678'
    - --port_out
    - '55027'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '53860'
    - --parallel_backend
    - process
    - --yaml_path
    - max256.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 55027
    port_out: 62214
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '55027'
    - --port_out
    - '62214'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '63308'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword