services:
  httpclient:
  - name: http
    app: httpclient
    model: http
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-http
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 54832
    port_out: 50358
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '54832'
    - --port_out
    - '50358'
    - --port_ctrl
    - '57484'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: Router0
    app: router
    model: base
    port_in: 50358
    port_out: 64325
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '50358'
    - --port_out
    - '64325'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '65322'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: Router1
    app: router
    model: base
    port_in: 64325
    port_out: 59741
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '64325'
    - --port_out
    - '59741'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '54774'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 59741
    port_out: 54832
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '59741'
    - --port_out
    - '54832'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '58700'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  preprocessor:
  - name: unary
    app: preprocessor
    model: unary
    port_in: 64325
    port_out: 50177
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '64325'
    - --port_out
    - '50177'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '49877'
    - --parallel_backend
    - process
    - --yaml_path
    - text.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-preprocessor:latest-unary
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 50177
    port_out: 51035
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '50177'
    - --port_out
    - '51035'
    - --socket_in
    - PULL_CONNECT
    - --port_ctrl
    - '61732'
    - --parallel_backend
    - process
    - --yaml_path
    - max256.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 51035
    port_out: 59741
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51035'
    - --port_out
    - '59741'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '56773'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword