services:
  httpclient:
  - name: http
    app: httpclient
    model: http
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-http
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 57105
    port_out: 65502
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '57105'
    - --port_out
    - '65502'
    - --port_ctrl
    - '55166'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: Router0
    app: router
    model: base
    port_in: 65502
    port_out: 58609
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '65502'
    - --port_out
    - '58609'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '49407'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: block
    app: router
    model: block
    port_in: 58609
    port_out: 53283
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '58609'
    - --port_out
    - '53283'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '52423'
    - --parallel_backend
    - process
    - --yaml_path
    - block_train.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-block
  - name: Router1
    app: router
    model: base
    port_in: 58609
    port_out: 62155
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '58609'
    - --port_out
    - '62155'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '50381'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 62155
    port_out: 57105
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62155'
    - --port_out
    - '57105'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '56641'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  preprocessor:
  - name: unary
    app: preprocessor
    model: unary
    port_in: 53283
    port_out: 51714
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '53283'
    - --port_out
    - '51714'
    - --socket_in
    - PULL_CONNECT
    - --port_ctrl
    - '55377'
    - --parallel_backend
    - process
    - --yaml_path
    - text.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-preprocessor:latest-unary
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 51714
    port_out: 62690
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51714'
    - --port_out
    - '62690'
    - --socket_in
    - PULL_CONNECT
    - --port_ctrl
    - '57360'
    - --parallel_backend
    - process
    - --yaml_path
    - max1024.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 62690
    port_out: 62155
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62690'
    - --port_out
    - '62155'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60258'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword