services:
  httpclient:
  - name: http
    app: httpclient
    model: http
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-http
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 57166
    port_out: 57515
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '57166'
    - --port_out
    - '57515'
    - --port_ctrl
    - '64250'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: log
    app: router
    model: log
    port_in: 57515
    port_out: 50721
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '57515'
    - --port_out
    - '50721'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '51721'
    - --parallel_backend
    - process
    - --yaml_path
    - LogRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-log
  - name: Router0
    app: router
    model: base
    port_in: 50721
    port_out: 54743
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '50721'
    - --port_out
    - '54743'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '57261'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 54743
    port_out: 57166
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '54743'
    - --port_out
    - '57166'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '58518'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  preprocessor:
  - name: unary
    app: preprocessor
    model: unary
    port_in: 50721
    port_out: 59083
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '50721'
    - --port_out
    - '59083'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '49644'
    - --parallel_backend
    - process
    - --yaml_path
    - text.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-preprocessor:latest-unary
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 59083
    port_out: 54731
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '59083'
    - --port_out
    - '54731'
    - --socket_in
    - PULL_CONNECT
    - --port_ctrl
    - '53664'
    - --parallel_backend
    - process
    - --yaml_path
    - max256.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 54731
    port_out: 54743
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '54731'
    - --port_out
    - '54743'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '64661'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword