apiVersion: v1
kind: Deployment
metadata:
  name: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: null
  template:
    metadata:
      labels:
        app: null
    spec:
      containers:
      - name: null
        image: null
        ports: null
        - containerPort: null
        volumeMounts:
          - name: null
            mountPath: /workspace