apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: null
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: null
  labels:
    app: null