apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sent_split
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: sent_split
          image: gnes-preprocessor:sent_split
          args: preprocess --port_in 59915 --port_out 58229 --socket_in PULL_CONNECT --socket_out PUB_BIND --port_ctrl 59552 --parallel_backend process --yaml_path services/preprocessors/sent_split/json_mode.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 59915
              protocol: TCP
            - name: out
              containerPort: 58229
              protocol: TCPresources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: sent_split
  clusterIP: None
    ports:
      - name: in
        port: 59915
        protocol: TCP
      - name: out
        port: 58229
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text_byte
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: text_byte
          image: gnes-encoder:text_byte
          args: encode --port_in 58229 --port_out 57116 --socket_in SUB_CONNECT --port_ctrl 49455 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 58229
              protocol: TCP
            - name: out
              containerPort: 57116
              protocol: TCPresources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: text_byte
  clusterIP: None
    ports:
      - name: in
        port: 58229
        protocol: TCP
      - name: out
        port: 57116
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keyword
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: keyword
          image: gnes-indexer:keyword
          args: index --port_in 57116 --port_out 60851 --socket_in PULL_CONNECT --socket_out PUSH_CONNECT --port_ctrl 64456 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 57116
              protocol: TCP
            - name: out
              containerPort: 60851
              protocol: TCPresources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: keyword
  clusterIP: None
    ports:
      - name: in
        port: 57116
        protocol: TCP
      - name: out
        port: 60851
        protocol: TCP


apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lvdb
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: lvdb
          image: gnes-indexer:lvdb
          args: index --port_in 58229 --port_out 60851 --socket_in SUB_CONNECT --socket_out PUSH_CONNECT --port_ctrl 61875 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 58229
              protocol: TCP
            - name: out
              containerPort: 60851
              protocol: TCPresources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: lvdb
  clusterIP: None
    ports:
      - name: in
        port: 58229
        protocol: TCP
      - name: out
        port: 60851
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Reduce
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: Reduce
          image: gnes-router:Reduce
          args: route --port_in 60851 --port_out 51953 --socket_out PUSH_CONNECT --port_ctrl 64465 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 60851
              protocol: TCP
            - name: out
              containerPort: 51953
              protocol: TCPresources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: Reduce
  clusterIP: None
    ports:
      - name: in
        port: 60851
        protocol: TCP
      - name: out
        port: 51953
        protocol: TCP



