apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sent_split
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: sent_split
          image: gnes-preprocessor:sent_split
          args: preprocess --port_in 63742 --port_out 61899 --socket_in PULL_CONNECT --socket_out PUB_BIND --port_ctrl 51805 --parallel_backend process --yaml_path services/preprocessors/sent_split/json_mode.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 63742
              protocol: TCP
            - name: out
              containerPort: 61899
              protocol: TCP
          resources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: sent_split
  clusterIP: None
    ports:
      - name: in
        port: 63742
        protocol: TCP
      - name: out
        port: 61899
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text_byte
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: text_byte
          image: gnes-encoder:text_byte
          args: encode --port_in 61899 --port_out 62648 --socket_in SUB_CONNECT --port_ctrl 60517 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 61899
              protocol: TCP
            - name: out
              containerPort: 62648
              protocol: TCP
          resources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: text_byte
  clusterIP: None
    ports:
      - name: in
        port: 61899
        protocol: TCP
      - name: out
        port: 62648
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keyword
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: keyword
          image: gnes-indexer:keyword
          args: index --port_in 62648 --port_out 54305 --socket_in PULL_CONNECT --socket_out PUSH_CONNECT --port_ctrl 50136 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 62648
              protocol: TCP
            - name: out
              containerPort: 54305
              protocol: TCP
          resources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: keyword
  clusterIP: None
    ports:
      - name: in
        port: 62648
        protocol: TCP
      - name: out
        port: 54305
        protocol: TCP


apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lvdb
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: lvdb
          image: gnes-indexer:lvdb
          args: index --port_in 61899 --port_out 54305 --socket_in SUB_CONNECT --socket_out PUSH_CONNECT --port_ctrl 55399 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 61899
              protocol: TCP
            - name: out
              containerPort: 54305
              protocol: TCP
          resources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: lvdb
  clusterIP: None
    ports:
      - name: in
        port: 61899
        protocol: TCP
      - name: out
        port: 54305
        protocol: TCP



apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Reduce
  volumeClaimTemplates:
    accessModes: 'ReadWriteOnce'
    resources:
      requests:
        storage: 
  template:
    spec:
      containers:
        - name: Reduce
          image: gnes-router:Reduce
          args: route --port_in 54305 --port_out 60442 --socket_out PUSH_CONNECT --port_ctrl 53919 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
          imagePullPolicy: null
          ports:
            - name: in
              containerPort: 54305
              protocol: TCP
            - name: out
              containerPort: 60442
              protocol: TCP
          resources:
            requests:
              cpu: 
              memory: 

apiVersion: v1
kind: Service
spec:
  selector:
    app: Reduce
  clusterIP: None
    ports:
      - name: in
        port: 54305
        protocol: TCP
      - name: out
        port: 60442
        protocol: TCP



