version: '3.4'
services:
  http:
    image: hub-httpclient:latest-http
    command: ''
    ports:
    - 80:80
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 49864 --port_out 61887 --port_ctrl 52896 --parallel_backend
      process
  Router0:
    image: gnes/gnes:latest-alpine
    command: route --port_in 61887 --port_out 49389 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 55348 --parallel_backend process --yaml_path BaseRouter
  unary:
    image: hub-preprocessor:latest-unary
    command: --port_in 49389 --port_out 59377 --socket_in SUB_CONNECT --port_ctrl
      62429 --parallel_backend process --yaml_path text.yml
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 59377 --port_out 63773 --socket_in PULL_CONNECT --port_ctrl
      64497 --parallel_backend process --yaml_path max256.yml
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 63773 --port_out 55801 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 53917 --parallel_backend process --yaml_path base.yml
  Router1:
    image: gnes/gnes:latest-alpine
    command: route --port_in 49389 --port_out 55801 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 64446 --parallel_backend process --yaml_path BaseRouter
  rerank:
    image: hub-router:latest-rerank
    command: --port_in 55801 --port_out 49864 --socket_out PUSH_CONNECT --port_ctrl
      49692 --parallel_backend process --yaml_path base.yml