version: '3.4'
services:
  http:
    image: hub-httpclient:latest-http
    command: ''
    ports:
    - 80:80
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 62339 --port_out 59997 --port_ctrl 63832 --parallel_backend
      process --check_version False
  Router0:
    image: gnes/gnes:latest-alpine
    command: route --port_in 59997 --port_out 52095 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 51726 --parallel_backend process --check_version False
      --yaml_path BaseRouter
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 52095 --port_out 54074 --socket_in SUB_CONNECT --port_ctrl
      57303 --parallel_backend process --check_version False --yaml_path max256.yml
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 54074 --port_out 50323 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 58040 --parallel_backend process --check_version False
      --yaml_path base.yml
  Router1:
    image: gnes/gnes:latest-alpine
    command: route --port_in 52095 --port_out 50323 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 59993 --parallel_backend process --check_version False
      --yaml_path BaseRouter
  rerank:
    image: hub-router:latest-rerank
    command: --port_in 50323 --port_out 62339 --socket_out PUSH_CONNECT --port_ctrl
      58360 --parallel_backend process --check_version False --yaml_path base.yml