version: '3.4'
services:
  http:
    image: hub-httpclient:latest-http
    command: ''
    ports:
    - 80:80
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 54218 --port_out 49752 --port_ctrl 64447 --parallel_backend
      process
  Router0:
    image: gnes/gnes:latest-alpine
    command: route --port_in 49752 --port_out 62765 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 65007 --parallel_backend process --yaml_path BaseRouter
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 62765 --port_out 58769 --socket_in SUB_CONNECT --port_ctrl
      58012 --parallel_backend process --yaml_path max256.yml
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 58769 --port_out 55857 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 60369 --parallel_backend process --yaml_path base.yml
  Router1:
    image: gnes/gnes:latest-alpine
    command: route --port_in 62765 --port_out 55857 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 62769 --parallel_backend process --yaml_path BaseRouter
  rerank:
    image: hub-router:latest-rerank
    command: --port_in 55857 --port_out 54218 --socket_out PUSH_CONNECT --port_ctrl
      61032 --parallel_backend process --yaml_path base.yml