services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 53027
    port_out: 62854
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '53027'
    - --port_out
    - '62854'
    - --port_ctrl
    - '62823'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 62854
    port_out: 51374
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62854'
    - --port_out
    - '51374'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '54867'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 1Gi
    cpu: 1Gi
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 51374
    port_out: 60919
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51374'
    - --port_out
    - '60919'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '59402'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 60919
    port_out: 57786
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '60919'
    - --port_out
    - '57786'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59810'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 51374
    port_out: 57786
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51374'
    - --port_out
    - '57786'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '64408'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: basereducerouter
    app: router
    model: basereducerouter
    port_in: 57786
    port_out: 53027
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '57786'
    - --port_out
    - '53027'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60567'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine