services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 64867
    port_out: 51889
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '64867'
    - --port_out
    - '51889'
    - --port_ctrl
    - '64874'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 51889
    port_out: 54483
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51889'
    - --port_out
    - '54483'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '64011'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 1Gi
    cpu: 1Gi
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 54483
    port_out: 53294
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '54483'
    - --port_out
    - '53294'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '53235'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 53294
    port_out: 59713
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '53294'
    - --port_out
    - '59713'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60097'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 54483
    port_out: 59713
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '54483'
    - --port_out
    - '59713'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '64020'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: basereducerouter
    app: router
    model: basereducerouter
    port_in: 59713
    port_out: 64867
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '59713'
    - --port_out
    - '64867'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '49390'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine