services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 49935
    port_out: 57746
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '49935'
    - --port_out
    - '57746'
    - --port_ctrl
    - '62313'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 57746
    port_out: 63014
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '57746'
    - --port_out
    - '63014'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '61954'
    - --parallel_backend
    - process
    - --yaml_path
    - hub/preprocessor/sentsplit/jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 500Mi
    cpu: 300m
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 63014
    port_out: 58554
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '63014'
    - --port_out
    - '58554'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '49310'
    - --parallel_backend
    - process
    - --yaml_path
    - hub/encoder/textbyte/max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 58554
    port_out: 62518
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '58554'
    - --port_out
    - '62518'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '54331'
    - --parallel_backend
    - process
    - --yaml_path
    - hub/indexer/keyword/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 63014
    port_out: 62518
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '63014'
    - --port_out
    - '62518'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '51170'
    - --parallel_backend
    - process
    - --yaml_path
    - hub/indexer/lvdb/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: reduce
    app: router
    model: basereducerouter
    port_in: 62518
    port_out: 49935
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '62518'
    - --port_out
    - '49935'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59855'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine