services:
  frontends:
  - name: Frontend0
    port_in: 64921
    port_out: 64970
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '64921'
    - --port_out
    - '64970'
    - --port_ctrl
    - '64169'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 64970
    port_out: 54189
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '64970'
    - --port_out
    - '54189'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '56443'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 500Mi
    cpu: 300m
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 54189
    port_out: 63055
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '54189'
    - --port_out
    - '63055'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '61633'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 63055
    port_out: 50577
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '63055'
    - --port_out
    - '50577'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '53531'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 54189
    port_out: 50577
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '54189'
    - --port_out
    - '50577'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '63536'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 50577
    port_out: 64921
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '50577'
    - --port_out
    - '64921'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '65312'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-router:reduce