services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 57502
    port_out: 53713
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '57502'
    - --port_out
    - '53713'
    - --port_ctrl
    - '60736'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 53713
    port_out: 61760
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '53713'
    - --port_out
    - '61760'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '59403'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 1Gi
    cpu: 1Gi
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 61760
    port_out: 65302
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '61760'
    - --port_out
    - '65302'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '60240'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 65302
    port_out: 55660
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '65302'
    - --port_out
    - '55660'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '62459'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 61760
    port_out: 55660
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '61760'
    - --port_out
    - '55660'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59098'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: basereducerouter
    app: router
    model: basereducerouter
    port_in: 55660
    port_out: 57502
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '55660'
    - --port_out
    - '57502'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '54849'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine