services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 56414
    port_out: 59806
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '56414'
    - --port_out
    - '59806'
    - --port_ctrl
    - '65022'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 59806
    port_out: 51225
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '59806'
    - --port_out
    - '51225'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '54558'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 1Gi
    cpu: 1Gi
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 51225
    port_out: 55432
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51225'
    - --port_out
    - '55432'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '55721'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 55432
    port_out: 53475
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '55432'
    - --port_out
    - '53475'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60339'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 51225
    port_out: 53475
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '51225'
    - --port_out
    - '53475'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '55576'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: basereducerouter
    app: router
    model: basereducerouter
    port_in: 53475
    port_out: 56414
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '53475'
    - --port_out
    - '56414'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60447'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine