services:
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 62299
    port_out: 61056
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '62299'
    - --port_out
    - '61056'
    - --port_ctrl
    - '53424'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  preprocessor:
  - name: sentsplit
    app: preprocessor
    model: sentsplit
    port_in: 61056
    port_out: 58086
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '61056'
    - --port_out
    - '58086'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '51431'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 1Gi
    cpu: 1Gi
    image: hub-preprocessor:latest-sentsplit
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 58086
    port_out: 62414
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '58086'
    - --port_out
    - '62414'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '57319'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 62414
    port_out: 49675
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '62414'
    - --port_out
    - '49675'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '50559'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword
  - name: lvdb
    app: indexer
    model: lvdb
    port_in: 58086
    port_out: 49675
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '58086'
    - --port_out
    - '49675'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '61326'
    - --parallel_backend
    - process
    - --num_parallel
    - '2'
    - --yaml_path
    - base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-lvdb
  router:
  - name: basereducerouter
    app: router
    model: basereducerouter
    port_in: 49675
    port_out: 62299
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '49675'
    - --port_out
    - '62299'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '53708'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine