version: '3.4'
services:
  base:
    image: hub-httpclient:latest-base
    command: ''
    ports:
    - 80:80
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 60324 --port_out 54666 --port_ctrl 50435 --parallel_backend
      process
  Router0:
    image: gnes/gnes:latest-alpine
    command: route --port_in 54666 --port_out 52984 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 60405 --parallel_backend process --yaml_path BaseRouter
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 52984 --port_out 64407 --socket_in SUB_CONNECT --port_ctrl
      53453 --parallel_backend process --yaml_path max256.yml
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 64407 --port_out 55439 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 58107 --parallel_backend process --yaml_path base.yml
  Router1:
    image: gnes/gnes:latest-alpine
    command: route --port_in 52984 --port_out 55439 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 58524 --parallel_backend process --yaml_path BaseRouter
  rerank:
    image: hub-router:latest-rerank
    command: --port_in 55439 --port_out 60324 --socket_out PUSH_CONNECT --port_ctrl
      59420 --parallel_backend process --yaml_path base.yml