services:
  httpclient:
  - name: base
    app: httpclient
    model: base
    port_in:
    port_out:
    ctrl_port:
    grpc_port:
    command: []
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-httpclient:latest-base
  frontend:
  - name: Frontend0
    app: frontend
    model: base
    port_in: 60324
    port_out: 54666
    ctrl_port:
    grpc_port:
    command:
    - frontend
    - --port_in
    - '60324'
    - --port_out
    - '54666'
    - --port_ctrl
    - '50435'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  router:
  - name: Router0
    app: router
    model: base
    port_in: 54666
    port_out: 52984
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '54666'
    - --port_out
    - '52984'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '60405'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: Router1
    app: router
    model: base
    port_in: 52984
    port_out: 55439
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '52984'
    - --port_out
    - '55439'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '58524'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseRouter
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes/gnes:latest-alpine
  - name: rerank
    app: router
    model: rerank
    port_in: 55439
    port_out: 60324
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '55439'
    - --port_out
    - '60324'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59420'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-router:latest-rerank
  encoder:
  - name: textbyte
    app: encoder
    model: textbyte
    port_in: 52984
    port_out: 64407
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '52984'
    - --port_out
    - '64407'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '53453'
    - --parallel_backend
    - process
    - --yaml_path
    - max256.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-encoder:latest-textbyte
  indexer:
  - name: keyword
    app: indexer
    model: keyword
    port_in: 64407
    port_out: 55439
    ctrl_port:
    grpc_port:
    command:
    - --port_in
    - '64407'
    - --port_out
    - '55439'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '58107'
    - --parallel_backend
    - process
    - --yaml_path
    - base.yml
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: hub-indexer:latest-keyword