
{{- define "statefulset" -}}
{{- $name := printf "%s-%s" .app .model -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  volumeClaimTemplates:
  - metadata:
      name: {{ $name }}
    spec:
      accessModes:
        - ReadWriteOnce
      {{- if .storage }}
      resources:
        requests:
          storage: {{ .storage }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .image }}
        args:
        {{- range .command }}
        - {{ . | quote }}
        {{- end }}
        imagePullPolicy: null
        ports:
        {{- if .port_in }}
        - name: in
          containerPort: {{ .port_in }}
          protocol: TCP
        {{- end }}
        {{- if .port_out }}
        - name: out
          containerPort: {{ .port_out }}
          protocol: TCP
        {{- end }}
        {{- if .grpc_port }}
        - name: grpc
          containerPort: {{ .grpc_port }}
          protocol: TCP
        {{- end }}
        {{- if .grpc_port }}
        - name: ctrl
          containerPort: {{ .port_ctrl }}
          protocol: TCP
        {{- end }}
          resources:
            requests:
              {{- if .cpu }}
              cpu: {{ .cpu }}
              {{- end }}
              {{- if .memory }}
              memory: {{ .memory }}
              {{- end }}

        {{- if .resources -}}
        {{- toYaml .resources | nindent 8 -}}
        {{- end -}}
{{- end -}}