version: '3.4'
services:
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 57116 --port_out 56758 --port_ctrl 59002 --parallel_backend
      process
  SentSplitPrep:
    image: gnes/gnes:latest-alpine
    command: preprocess --port_in 56758 --port_out 64844 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 54376 --parallel_backend process --yaml_path
      ../../../services/preprocessors/sent-split/json-mode.yml
    deploy:
      replicas: 2
  SiameseBertEncoder:
    image: gnes/gnes:latest-alpine
    command: encode --port_in 64844 --port_out 57095 --socket_in SUB_CONNECT --port_ctrl
      53308 --parallel_backend process --yaml_path ../../../services/encoders/siamese-bert/dim-64.yml
    deploy:
      replicas: 2
  FaissIdx:
    image: gnes/gnes:latest-alpine
    command: index --port_in 57095 --port_out 60933 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 50122 --parallel_backend process --yaml_path ../../../services/indexers/faiss-cpu/base.yml
    deploy:
      replicas: 2
  TextByteEncoder:
    image: gnes/gnes:latest-alpine
    command: encode --port_in 64844 --port_out 49364 --socket_in SUB_CONNECT --port_ctrl
      63083 --parallel_backend process --yaml_path ../../../services/encoders/text-byte/max-256.yml
    deploy:
      replicas: 2
  KeywordIdx:
    image: gnes/gnes:latest-alpine
    command: index --port_in 49364 --port_out 60933 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 50194 --parallel_backend process --yaml_path ../../../services/indexers/keyword/base.yml
    deploy:
      replicas: 2
  LevelDBIdx:
    image: gnes/gnes:latest-alpine
    command: index --port_in 64844 --port_out 60933 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 52664 --parallel_backend process --yaml_path ../../../services/indexers/lvdb/base.yml
    deploy:
      replicas: 2
  Reduce:
    image: gnes/gnes:latest-alpine
    command: route --port_in 60933 --port_out 57116 --socket_out PUSH_CONNECT --port_ctrl
      52008 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2