
{{- with .Values.services }}
{{- range list .frontend .preprocessor .encoder .indexer .router }}
{{- range . }}
---
{{ include "statefulset" .}}
---
{{ include "service" .}}
{{ end }}
{{ end }}
{{ end }}