name: fever
base: bert
repo: gs://poloma-models
task: classification
data:
  source: postgres
  schema: model_data
  train: fever_train
  test: fever_test
labels:
  - SUPPORTS
  - REFUTES
  - NEI
training:
  checkpoint: bert-base-uncased
  epochs: 3
  learning_rate: 1e-05