name: mnli
base: bert
repo: gs://poloma-models
task: classification
data:
  source: postgres
  schema: mnli
  train: train_set
  test: test_set
labels:
  - neutral
  - contradiction
  - entailment
training:
  checkpoint: bert-base-uncased
  epochs: 3
  learning_rate: 1e-05