version: '3.4'
services:
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 61973 --port_out 54596 --port_ctrl 57120 --parallel_backend
      process
    ports:
    - 8800:8800
  sentsplit:
    image: hub-preprocessor:latest-sentsplit
    command: --port_in 54596 --port_out 60639 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 56881 --parallel_backend process --num_parallel 2 --yaml_path
      jsonmode.yml
    deploy:
      replicas: 2
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 60639 --port_out 58737 --socket_in SUB_CONNECT --port_ctrl
      54010 --parallel_backend process --num_parallel 2 --yaml_path max256.yml
    deploy:
      replicas: 2
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 58737 --port_out 61340 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 64855 --parallel_backend process --num_parallel 2 --yaml_path
      base.yml
    deploy:
      replicas: 2
  lvdb:
    image: hub-indexer:latest-lvdb
    command: --port_in 60639 --port_out 61340 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 54746 --parallel_backend process --num_parallel 2 --yaml_path
      base.yml
    deploy:
      replicas: 2
  basereducerouter:
    image: gnes/gnes:latest-alpine
    command: route --port_in 61340 --port_out 61973 --socket_out PUSH_CONNECT --port_ctrl
      57894 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2