version: '3.4'
services:
  Frontend0:
    image: gnes/gnes:latest-alpine
    command: frontend --port_in 60716 --port_out 54946 --port_ctrl 59522 --parallel_backend
      process
    ports:
    - 8800:8800
  sentsplit:
    image: hub-preprocessor:latest-sentsplit
    command: --port_in 54946 --port_out 52112 --socket_in PULL_CONNECT --socket_out
      PUB_BIND --port_ctrl 56050 --parallel_backend process --num_parallel 2 --yaml_path
      jsonmode.yml
    deploy:
      replicas: 2
  textbyte:
    image: hub-encoder:latest-textbyte
    command: --port_in 52112 --port_out 64398 --socket_in SUB_CONNECT --port_ctrl
      53375 --parallel_backend process --num_parallel 2 --yaml_path max256.yml
    deploy:
      replicas: 2
  keyword:
    image: hub-indexer:latest-keyword
    command: --port_in 64398 --port_out 61173 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 64890 --parallel_backend process --num_parallel 2 --yaml_path
      base.yml
    deploy:
      replicas: 2
  lvdb:
    image: hub-indexer:latest-lvdb
    command: --port_in 52112 --port_out 61173 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 62904 --parallel_backend process --num_parallel 2 --yaml_path
      base.yml
    deploy:
      replicas: 2
  basereducerouter:
    image: gnes/gnes:latest-alpine
    command: route --port_in 61173 --port_out 60716 --socket_out PUSH_CONNECT --port_ctrl
      56512 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2