services:
  frontends:
  - name: Frontend0
    port_in: 59925
    port_out: 53371
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '59925'
    - --port_out
    - '53371'
    - --port_ctrl
    - '54679'
    - --parallel_backend
    - process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 53371
    port_out: 52338
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '53371'
    - --port_out
    - '52338'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '53747'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 52338
    port_out: 65388
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '52338'
    - --port_out
    - '65388'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '51319'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 65388
    port_out: 49706
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '65388'
    - --port_out
    - '49706'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '50862'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 52338
    port_out: 49706
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '52338'
    - --port_out
    - '49706'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '62916'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 49706
    port_out: 59925
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '49706'
    - --port_out
    - '59925'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59154'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce