services:
  frontends:
  - name: Frontend0
    port_in: 54021
    port_out: 49867
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '54021'
    - --port_out
    - '49867'
    - --port_ctrl
    - '62665'
    - --parallel_backend
    - process
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 49867
    port_out: 63468
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '49867'
    - --port_out
    - '63468'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '49209'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage: 1Gi
    memory: 500Mi
    cpu: 300m
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 63468
    port_out: 60178
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '63468'
    - --port_out
    - '60178'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '58742'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 60178
    port_out: 49356
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '60178'
    - --port_out
    - '49356'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '57041'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 63468
    port_out: 49356
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '63468'
    - --port_out
    - '49356'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '51950'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 49356
    port_out: 54021
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '49356'
    - --port_out
    - '54021'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '59294'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage: 500Mi
    memory: 500Mi
    cpu: 300m
    image: gnes-router:reduce