services:
  frontends:
  - name: Frontend0
    port_in: 65042
    port_out: 57848
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '65042'
    - --port_out
    - '57848'
    - --port_ctrl
    - '49563'
    - --parallel_backend
    - process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 57848
    port_out: 60857
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '57848'
    - --port_out
    - '60857'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '58373'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 60857
    port_out: 60447
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '60857'
    - --port_out
    - '60447'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '61950'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 60447
    port_out: 54994
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '60447'
    - --port_out
    - '54994'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '57570'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 60857
    port_out: 54994
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '60857'
    - --port_out
    - '54994'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '57982'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 54994
    port_out: 65042
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '54994'
    - --port_out
    - '65042'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60530'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce