services:
  frontends:
  - name: Frontend0
    port_in: 58277
    port_out: 57148
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '58277'
    - --port_out
    - '57148'
    - --port_ctrl
    - '56513'
    - --parallel_backend
    - process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 57148
    port_out: 59430
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '57148'
    - --port_out
    - '59430'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '54886'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 59430
    port_out: 59987
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '59430'
    - --port_out
    - '59987'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '59635'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 59987
    port_out: 52512
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '59987'
    - --port_out
    - '52512'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '64552'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 59430
    port_out: 52512
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '59430'
    - --port_out
    - '52512'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '55705'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 52512
    port_out: 58277
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '52512'
    - --port_out
    - '58277'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '55583'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce