services:
  frontends:
  - name: Frontend0
    port_in: 60740
    port_out: 58037
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '60740'
    - --port_out
    - '58037'
    - --port_ctrl
    - '58556'
    - --parallel_backend
    - process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 58037
    port_out: 55052
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '58037'
    - --port_out
    - '55052'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '55627'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 55052
    port_out: 52281
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '55052'
    - --port_out
    - '52281'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '56768'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 52281
    port_out: 61275
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '52281'
    - --port_out
    - '61275'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '56315'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 55052
    port_out: 61275
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '55052'
    - --port_out
    - '61275'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '62826'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 61275
    port_out: 60740
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '61275'
    - --port_out
    - '60740'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '56044'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce