services:
  frontends:
  - name: Frontend0
    port_in: 50143
    port_out: 64629
    ctrl_port:
    grpc_port: 8800
    command: frontend --port_in 50143 --port_out 64629 --port_ctrl 64976 --parallel_backend
      process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sent_split
    port_in: 64629
    port_out: 59329
    ctrl_port:
    grpc_port:
    command: preprocess --port_in 64629 --port_out 59329 --socket_in PULL_CONNECT
      --socket_out PUB_BIND --port_ctrl 64946 --parallel_backend process --yaml_path
      services/preprocessors/sent_split/json_mode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sent_split
  encoders:
  - name: text_byte
    port_in: 59329
    port_out: 64090
    ctrl_port:
    grpc_port:
    command: encode --port_in 59329 --port_out 64090 --socket_in SUB_CONNECT --port_ctrl
      55805 --parallel_backend process --yaml_path services/encoders/text_byte/max_256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:text_byte
  indexers:
  - name: keyword
    port_in: 64090
    port_out: 65362
    ctrl_port:
    grpc_port:
    command: index --port_in 64090 --port_out 65362 --socket_in PULL_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 53838 --parallel_backend process --yaml_path services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 59329
    port_out: 65362
    ctrl_port:
    grpc_port:
    command: index --port_in 59329 --port_out 65362 --socket_in SUB_CONNECT --socket_out
      PUSH_CONNECT --port_ctrl 54011 --parallel_backend process --yaml_path services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 65362
    port_out: 50143
    ctrl_port:
    grpc_port:
    command: route --port_in 65362 --port_out 50143 --socket_out PUSH_CONNECT --port_ctrl
      56226 --parallel_backend process --yaml_path BaseReduceRouter --num_part 2
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce