services:
  frontends:
  - name: Frontend0
    port_in: 59845
    port_out: 51144
    ctrl_port:
    grpc_port: 8800
    command:
    - frontend
    - --port_in
    - '59845'
    - --port_out
    - '51144'
    - --port_ctrl
    - '54438'
    - --parallel_backend
    - process
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-frontend:Frontend0
  preprocessors:
  - name: sentsplit
    port_in: 51144
    port_out: 63038
    ctrl_port:
    grpc_port:
    command:
    - preprocess
    - --port_in
    - '51144'
    - --port_out
    - '63038'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUB_BIND
    - --port_ctrl
    - '59997'
    - --parallel_backend
    - process
    - --yaml_path
    - services/preprocessors/sentsplit/jsonmode.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-preprocessor:sentsplit
  encoders:
  - name: textbyte
    port_in: 63038
    port_out: 50390
    ctrl_port:
    grpc_port:
    command:
    - encode
    - --port_in
    - '63038'
    - --port_out
    - '50390'
    - --socket_in
    - SUB_CONNECT
    - --port_ctrl
    - '50566'
    - --parallel_backend
    - process
    - --yaml_path
    - services/encoders/textbyte/max256.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-encoder:textbyte
  indexers:
  - name: keyword
    port_in: 50390
    port_out: 59530
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '50390'
    - --port_out
    - '59530'
    - --socket_in
    - PULL_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '55521'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/keyword/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:keyword
  - name: lvdb
    port_in: 63038
    port_out: 59530
    ctrl_port:
    grpc_port:
    command:
    - index
    - --port_in
    - '63038'
    - --port_out
    - '59530'
    - --socket_in
    - SUB_CONNECT
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '60121'
    - --parallel_backend
    - process
    - --yaml_path
    - services/indexers/lvdb/base.yml
    replicas: 2
    storage:
    memory:
    cpu:
    image: gnes-indexer:lvdb
  routers:
  - name: reduce
    port_in: 59530
    port_out: 59845
    ctrl_port:
    grpc_port:
    command:
    - route
    - --port_in
    - '59530'
    - --port_out
    - '59845'
    - --socket_out
    - PUSH_CONNECT
    - --port_ctrl
    - '56069'
    - --parallel_backend
    - process
    - --yaml_path
    - BaseReduceRouter
    - --num_part
    - '2'
    replicas: 1
    storage:
    memory:
    cpu:
    image: gnes-router:reduce